### ISSUE TITLE
学习写loon用的js后缀文件需要学习什么编程课？

### ISSUE THREAD

**Issue by wushengtolearn** [chiupam/tutorial#1]

**Comment by chiupam** [comment]
需要学习js的 还要配合开发者文档看看 但我都不会 因为我只是一个平平无奇的写教程小能手！

**Comment by wushengtolearn** [comment]
> 需要学习js的 还要配合开发者文档看看 但我都不会 因为我只是一个平平无奇的写教程小能手！

今天就定一个小目标，成为一个平平无奇的古天乐

**Comment by chiupam** [comment]
冲冲冲！
