### ISSUE TITLE
BoxJS地址无法打开，这个怎么解决？

### ISSUE THREAD

**Issue by AndrewXiang** [chiupam/tutorial#4]

**Comment by YamTian** [comment]
检查是否正确添加了相关插件 以及检查对应插件使用的地址是boxjs.com还是boxjs.net 如果是跳转至ww6.boxjs.net这个网站 尝试在Loon首页点击Mitm并添加boxjs.net这个主机名

**Comment by chiupam** [comment]
检查是否正确添加了相关插件 以及检查对应插件使用的地址是boxjs.com还是boxjs.net 如果是跳转至ww6.boxjs.net这个网站 尝试在Loon首页点击Mitm并添加boxjs.net这个主机名 如果是黑白屏的情况请查阅以下网站 https://chavyleung.gitbook.io/boxjs/advanced/aid 并在Loon中运行该网站中给出的脚本代码

**Comment by AndrewXiang** [comment]
谢谢您的耐心解答，已经解决了。没有填写重写的引用地址。
另还有个问题，在彩云天气的这个插件下，发现提醒的天气，并不是实时获取我当前的位置，这个怎么解决？

**Comment by chiupam** [comment]
此问题不属于 Loon 的使用问题 故此处不予解答 
建议前往彩云天气脚本作者 Peng-YM 库提出 [issues](https://github.com/Peng-YM/QuanX/issues) 传送门 https://github.com/Peng-YM/QuanX/issues

**Comment by AndrewXiang** [comment]
好的，不过已经自己解决了。谢谢你~~~
