### ISSUE TITLE
最近boxjs打不开 

### ISSUE THREAD

**Issue by RunHui1996** [chiupam/tutorial#5]
quanx 之前还好好的最近 进去就safari浏览器无法打开网页,因为您的iPhone尚未接入互联网 手机已越狱 重启后解除越狱就一切正常 秒进 重新越狱了又这样子 如何解决 引用重写一直都是打开的

**Comment by chiupam** [comment]
~~这个问题在了我能力的解决范围之外 越狱的话会出现奇怪的问题那是肯定的 但也不是人人都是幸运儿 我能给你的只是建议 我建议你可以给开发者发邮件询问一番 邮箱：support@quantumult.crossutility.com~~

**Comment by chiupam** [comment]
不好意思我理解错你的问题了 你的问题是说你使用qx无法进入boxjs了对吧？你可以检查一下自己的配置噢 boxjs的重写地址在之前从gitee更换为github了 你查一下是不是这个原因 点击查看[相关通知](https://t.me/chavyscripts/229) 另外你也可以观看大飞的qx系列视频[第五期](https://youtu.be/skod8MB5u7E) 自检一下是否出现视频里的问题

**Comment by RunHui1996** [comment]
行吧

**Comment by RunHui1996** [comment]
对的 我用小火箭可以打开boxjs 用quanx反而不行 重写地址都是正确的 只要丢失越狱环境就能打开

**Comment by chiupam** [comment]
那可能真的与越狱环境有关了 这个试着发邮件给开发者碰碰运气 support@quantumult.crossutility.com(虽然我觉得huaqian会回复让你别越) 或者你也与boxjs开发者[提出issue](https://github.com/chavyleung/scripts/issues/new)看看能得到什么信息

**Comment by clickear** [comment]
> 对的 我用小火箭可以打开boxjs 用quanx反而不行 重写地址都是正确的 只要丢失越狱环境就能打开

https://github.com/chavyleung/scripts/issues/161 参考这个，解决处理
