### ISSUE TITLE
关于脚本请求的总是400的问题

### ISSUE THREAD

**Issue by leoding** [chiupam/tutorial#6]
打算自己用Loon脚本做一些签到操作，但是在发起请求时总是返回400，图片如下：
![cc24521b7e89b6df8cad188848f0d16](https://user-images.githubusercontent.com/3339737/180389678-31af219a-1c5d-46d9-ade4-6b95eea82bfb.jpg)
![1abec6d060bc6561fe380a3515f22af](https://user-images.githubusercontent.com/3339737/180389761-8285a32c-41fc-45d3-98ba-0bdd4443f00e.jpg)

很费解，更改了自带的示例js的URL但是返回总是400，也不知道是什么问题。。。

**Comment by chiupam** [comment]
```javascripts
/*
 * Loon script example
 */
//log
console.log('This is a log');

//http get params
var params = {
    url:"https://www.baidu.com/",
    header: {
        "Host":"api.example.com",
        "Content-Type": "application/json",
    },
    body: "string"
}

$httpClient.get('https://www.baidu.com/',function(error, response, data){
    console.log(response);
});

//http get
$httpClient.get(params,function(error, response, data){
    console.log(response);
});

//http post
$httpClient.post(params,function(error, response, data){
    console.log(response);
});

//notification
$notification.post('title<String>', 'subtitle<String>', 'body<String>')

//persistentStore
$persistentStore.write('data<String>', 'key<String>')
$persistentStore.read('key<String>')
```

**Comment by chiupam** [comment]
因为地址错了 正确的地址应该是 `https://www.baidu.com/` 而不是 `https://www.baidu.com`

**Comment by leoding** [comment]
谢谢，本来通过共享账号想试用一下圈X和Loon哪个使用起来更方便，然后自己再购买，但是发现同样的JS逻辑，只是改了请求对象($task.fetch/$httpClient)，Loon返回结果很是不同。我是先写了圈X的脚本，可以达到预期并正常执行，然后迁移到Loon里，首先就发生上面的斜杠("/")问题（搞不明白这个斜杠的意义）；然后到JS最后一步，怎么都不返回data数据，response状态是200，但error一直报：Empty response data.；还有一个奇怪现象，只有刚开启Loon后的第一次脚本运行，中间换取cookie的请求能返回data(html页面)，后续调试执行就获取不到相应的html页面了。不明白Loon的$httpClient是怎么个请求逻辑。

**Comment by chiupam** [comment]
请求逻辑啥的我也不怕了 只能通过群组去问作者3k才行 你如果想要写个简单的签到 你可以参考我下面这个脚本 掌上飞车每日签到 https://github.com/chiupam/surge/blob/main/scripts/javascripts/zsfc.js

**Comment by chiupam** [comment]
对于哪两个软件来说 你如果能从js来确定那也可以 毕竟用得顺手是重要的 另外 我觉得Loon的上手难度低 UI操作起来很快捷方便 官方群交流也比较友好（对比某些群来说）qx我有些时日不用了 它就偏技术人员 能用起来和Loon确实麻烦一些 但网络调试界面十分清晰 更偏向动手能力强的人吧 还有就是价格 你都可以参考一下

**Comment by leoding** [comment]
已破案，与作者联系过了，是因为Loon对返回结果的数据大小做了限制，当结果数据大于1M时，Loon不做返回，所以一直报：Empty response data错误。
